#!/bin/bash
echo "starting..."
if [ -f "./backups/bot.py" ]; then
	rm ./backups/bot.py
fi
if [ -f "./backups/Dockerfile" ]; then
	rm ./backups/Dockerfile
fi
if [ -f "./backups/docker-compose.yml" ]; then
	rm ./backups/docker-compose.yml
fi
echo -e "...\n...\n..."
cp ./bot.py ./backups/bot.py
cp ./Dockerfile ./backups/Dockerfile
cp ./docker-compose.yml ./backups/docker-compose.yml
echo "done!!!"